### ISSUE TITLE
Code obsolete ??

### ISSUE THREAD

**Issue by Rishi-Goyal** [raunaktamang/automatewhatsapp#2]
So I was writing a code for the same, and I discovered that whatsapp web changed the titles of the elements that you are accessing in your code.
I changed them but even after that the code is not working properly since no msg is being typed in the msg_box 
If you know why this is happening please do help me out. Thank you.

**Comment by cyber-hoax** [comment]
Click the inspect element on the message box on any contact and use the class name in msg_box that might help you if this not work then try to use above class or below class name of the copied class

**Comment by Rishi-Goyal** [comment]
I have used the new class titles in the code, but it doesn't seem to be sending the keys to the msg_box element
If you want, I can share the code with you, and you can check if there is something that I am doing wrong

**Comment by cyber-hoax** [comment]
yeah please !

**Comment by Rishi-Goyal** [comment]
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import random
import time

  
# create webdriver object
i = 0
a = "https://web.whatsapp.com/"


driver = webdriver.Firefox()

    
c = random.randint(220,360)
driver.get(a)
wait = WebDriverWait(driver, 600)
name = input('enter the name of user ')
msg = input('enter your message ')
count = int(input("enter the count "))
input('enter after scanning QR code')


user = driver.find_element_by_xpath('//span[@title = "{}"]'.format(name))


user.click()
msg_box = driver.find_element_by_class_name('_2A8P4')

#msg_box.send_keys(msg)
#button = driver.find_element_by_class_name('_1E0Oz')
#button.click()
inp_xpath = '//div[@class="input"][@dir="auto"][@data-tab="1"]'
input_box = wait.until(EC.presence_of_element_located((By.XPATH, inp_xpath)))
for i in range(100):
    input_box.send_keys(msg + Keys.ENTER)
    time.sleep(1)



This is the code, I dont know why it is not working

**Comment by cyber-hoax** [comment]
what is the error you're getting ??

**Comment by cyber-hoax** [comment]
> Click the inspect element on the message box on any contact and use the class name in msg_box that might help you if this not work then try to use above class or below class name of the copied class

**Comment by Rishi-Goyal** [comment]
I get the error that the send button element could not be found, but that is because the element only comes into view when something is typed in the message box, so there is something wrong with the sending keys to the message box.

**Comment by cyber-hoax** [comment]
in for loops.send_keys is not working it cannot get send_keys

**Comment by Rishi-Goyal** [comment]
What do you mean by that ? send_keys is not working for what reason ?

**Comment by cyber-hoax** [comment]
Nothing and yeah I checked it I can't find why is this happening not getting a clue. I searched it  can be the reason I found that the frame should be switched, in this case element is not inside a frame tag

**Comment by Sidharth-S** [comment]
Most times , command to click a button is given when the Whatsapp is on its loading screen ;
Just try get_screenshot_as_file to check the above

**Comment by mudassir567** [comment]
@cyber-hoax  Can I contribute to this issue.?

**Comment by cyber-hoax** [comment]
@mudassir567 yes sure  why not if you can please feel free to :)

**Comment by mudassir567** [comment]
> @mudassir567 yes sure why not if you can please feel free to :)

Thankyou for letting we work on the project . Appreciate it

**Comment by mudassir567** [comment]
@cyber-hoax  Thankyou for letting we work on the project . Appreciate it
Please review the PR and Merge :relaxed:

**Comment by cyber-hoax** [comment]
> @mudassir567 that's great bro! :) thank you so much for taking your time to fix it
